### ISSUE TITLE
Circle configuration extraction mismatched from node version

### ISSUE THREAD

**Issue by kbacha** [tagliala/coveralls-ruby-reborn#30]
It appears that the node CLI tool extracts the environment slightly differently:

https://github.com/nickmerwin/node-coveralls/blob/master/lib/getOptions.js#L56-L58

vs

https://github.com/tagliala/coveralls-ruby-reborn/blob/main/lib/coveralls/configuration.rb#L70-L74

I think that this may be a relic of how circle behaved in circle v1.0, but we may want to mirror the other gem

**Comment by tagliala** [comment]
Hi @kbacha, please give a try to this branch: https://github.com/tagliala/coveralls-ruby-reborn/tree/fix-circleci
