### ISSUE TITLE
The README doesn't describe how to setup and use the gem

### ISSUE THREAD

**Issue by nevinera** [tagliala/coveralls-ruby-reborn#44]
Compared the the [docs](https://github.com/lemurheavy/coveralls-ruby#readme) for the old/replaced gem - you can see the difference. The current readme here basically says "install the gem. Unless you're using github actions, then don't".

The "read the docs" [link](https://docs.coveralls.io/ruby-and-rails) takes us to a page on the coveralls site that doesn't give us any of that information either, but perhaps it used to? Now it links to two gems (including this one), and says to "See each project’s README for instructions".

If I knew the gem well enough, I'd try to write and PR such instructions, but I'm writing in because I'm having a devil of a time working it out from the code already -.-

**Comment by tagliala** [comment]
Hi!

At the time I've forked, lemurheavy/coveralls-ruby@80ddd4bcbdc9dc7dfbb6989803efba7279aea36e was not there, and I did not rebase from master

I think I should merge that PR here with adaptations, because it was probably the content of the linked web page

After a quick reading, I think that https://github.com/lemurheavy/coveralls-ruby's readme is  what you are looking for

**Comment by nevinera** [comment]
Aye, I looked through it, I just wasn't sure how much to trust it - you forked quite a while ago, so I assumed you had substantial change accumulated. I ended up sorting myself out using the coverals circleci orb instead. If you think that README is still accurate though, I can throw a PR together to port it over, give me a minute :-)

**Comment by nevinera** [comment]
https://github.com/tagliala/coveralls-ruby-reborn/pull/45 - could you take a look through it and make sure everything's still right though? If you've changed any of this stuff relative to the original, I probably wouldn't notice, and I could easily have missed a reference or so to the older gem-name.

**Comment by tagliala** [comment]
Closede by #45
