### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by sylvainbx** [tagliala/coveralls-ruby-reborn#7]
When sending test data to coveralls, from the CLI (using `bundle exec coveralls push`), the following error is raised:
```
Coveralls encountered an exception:
OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 state=error: no protocols available
```

Version installed: 0.17.0
Rails version: 5.2.4.3
Ruby version: 2.6.5

**Comment by tagliala** [comment]
@sylvainbx thanks for the PR

Could you please also give a try to this branch?  `chore/refactor-http-client`

I've switched to auto negotiation and removed some code that I think it was related to Ruby < 2.0

**Comment by sylvainbx** [comment]
Of course!
I've just made a test using the chore/refactor-http-client branch, as you asked, and it worked fine.

**Comment by tagliala** [comment]
@sylvainbx thanks! I'm going to merge and release a new version of this gem

**Comment by tagliala** [comment]
0.18.0 released
